imports:
    - { resource: tables.yml }

services:
    kaerol.simpleshop.order_an_item:
        class: kaerol\simpleshop\controller\order_an_item
        arguments:
            - '@service_container'
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@notification_manager'
            - '@request'
            - '@user'
            - '@language'

    kaerol.simpleshop.sale_report:
        class: kaerol\simpleshop\controller\sale_report
        arguments:
            - '@service_container'
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@notification_manager'
            - '@request'
            - '@user'
            - '@language'
            - '@kaerol.simpleshop.order_statistic'

    kaerol.simpleshop.posting_listener:
        class: kaerol\simpleshop\event\posting_listener
        arguments:
            - '@service_container'
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@dispatcher'
            - '@notification_manager'
            - '@request'
            - '@template'
            - '@user'
            - '@kaerol.simpleshop.order_statistic'
        tags:
            - { name: event.listener }		
            
    kaerol.simpleshop.order_statistic:
        class: kaerol\simpleshop\includes\order_statistic
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '@user'
            - '@language'